In [2]:
import numpy as np
import pandas as pd

In [3]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
from sklearn.metrics.pairwise import cosine_similarity

Using TensorFlow backend.


In [4]:
df = pd.read_csv('1.csv')
df = df[['name','rate','location','dish_liked','cuisines','approx_cost','neighbourhood']]
df.drop_duplicates('name', inplace=True)
df.dropna(subset=['cuisines'], inplace=True)

In [5]:
import string
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

df["cuisines"] = df["cuisines"].apply(lambda text: remove_punctuation(text))
df['addr'] = df['neighbourhood'] +' '+ df['location']
df.set_index('name', inplace=True)
indices = pd.Series(df.index)

In [6]:
df

rate  \
name                                                       
Jalsa                                                4.1   
Spice Elephant                                       4.1   
San Churro Cafe                                      3.8   
Addhuri Udupi Bhojana                                3.7   
Grand Village                                        3.8   
...                                                  ...   
Chime - Sheraton Grand Bengaluru Whitefield Hot...   4.3   
The Nest - The Den Bengaluru                         3.4   
Nawabs Empire                                        3.2   
SeeYa Restaurant                                     3.3   
Plunge - Sheraton Grand Bengaluru Whitefield Ho...   NaN   

                                                                      location  \
name                                                                             
Jalsa                                                             Banashankari   
Spice Elephant                                                    Banashankari   
San Churro Cafe                                                   Banashankari   
Addhuri Udupi Bhojana                                             Banashankari   
Grand Village                                                     Basavanagudi   
...                                                                        ...   
Chime - Sheraton Grand Bengaluru Whitefield Hot...  ITPL Main Road, Whitefield   
The Nest - The Den Bengaluru                        ITPL Main Road, Whitefield   
Nawabs Empire                                       ITPL Main Road, Whitefield   
SeeYa Restaurant                                                      KR Puram   
Plunge - Sheraton Grand Bengaluru Whitefield Ho...                  Whitefield   

                                                                                           dish_liked  \
name                                                                                                    
Jalsa                                               Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
Spice Elephant                                      Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   
San Churro Cafe                                     Churros, Cannelloni, Minestrone Soup, Hot Choc...   
Addhuri Udupi Bhojana                                                                     Masala Dosa   
Grand Village                                                                     Panipuri, Gol Gappe   
...                                                                                               ...   
Chime - Sheraton Grand Bengaluru Whitefield Hot...                       Cocktails, Pizza, Buttermilk   
The Nest - The Den Bengaluru                                                                      NaN   
Nawabs Empire                                                                                     NaN   
SeeYa Restaurant                                                                                  NaN   
Plunge - Sheraton Grand Bengaluru Whitefield Ho...                                                NaN   

                                                                                cuisines  \
name                                                                                       
Jalsa                                                       North Indian Mughlai Chinese   
Spice Elephant                                                 Chinese North Indian Thai   
San Churro Cafe                                                     Cafe Mexican Italian   
Addhuri Udupi Bhojana                                          South Indian North Indian   
Grand Village                                                    North Indian Rajasthani   
...                                                                                  ...   
Chime - Sheraton Grand Bengaluru Whitefield Hot...                           Finger Food   
The Nest -

In [7]:
l = [i for i in df['addr']]
l2 = [i for i in df['cuisines']]
l3 = [i for i in df['dish_liked']]

In [8]:
dish=[]
for i in l3:
    if pd.isna(i):
        dish.append('')
    else:
        dish.append(''.join(i.split(',')))

In [9]:
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in l]
encoded_docs2 = [one_hot(d, vocab_size) for d in l2]
encoded_docs3 = [one_hot(d, vocab_size) for d in dish]

max_length = 10
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
padded_docs2 = pad_sequences(encoded_docs2, maxlen=max_length, padding='post')
padded_docs3 = pad_sequences(encoded_docs3, maxlen=max_length, padding='post')


In [10]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 10, 8)             400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 80)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 81        
Total params: 481
Trainable params: 481
Non-trainable params: 0
_________________________________________________________________
None


In [11]:
# fit the model
embd = model.predict(padded_docs)
embd2 = model.predict(padded_docs2)
embd3 = model.predict(padded_docs3)

In [12]:
embd,embd2,embd3

(array([[0.5022929 ],
        [0.5022929 ],
        [0.5022929 ],
        ...,
        [0.5126716 ],
        [0.51264906],
        [0.51373714]], dtype=float32),
 array([[0.50852466],
        [0.50823224],
        [0.50693524],
        ...,
        [0.5053636 ],
        [0.5060385 ],
        [0.50904024]], dtype=float32),
 array([[0.5217099 ],
        [0.50056547],
        [0.50743616],
        ...,
        [0.512577  ],
        [0.512577  ],
        [0.512577  ]], dtype=float32))

In [41]:
sim=[]
for i in range(indices.shape[0]):
    #sim.append([embd[i][0],embd2[i][0],embd3[i][0]])
    #sim.append([embd[i][0],embd2[i][0],embd3[i][0]]) 
    sim.append([embd[i][0],embd2[i][0]])

In [42]:
sim[0]

[0.5022929, 0.50852466]

In [49]:
def rec(name):
    idx = indices[indices == name].index[0]
    corr,reco = [],[]
    for i in range(len(sim)):
        #corr.append( (cosine_similarity([sim[idx]],[sim[i]])[0][0], i))
        cs = cosine_similarity([sim[idx]],[sim[i]])[0][0]
        if cs>=1:
            corr.append((cs,i))
     
    corr = sorted(corr,key = lambda x:x[0], reverse=True)
    reco = [c[1] for c in corr]
    reco.remove(idx)
    print('Coverage = ',(len(corr)*100/df.shape[0]),'Percent')
    
    return df.iloc[reco[:11]]
    

    
rec("Furry Fairy Paw Paradise")

Coverage =  5.441712204007286 Percent


rate           location  \
name                                                      
Spice Elephant                   4.1       Banashankari   
Burger King                      3.2       Basavanagudi   
Ande Ka Funda                    3.8       Banashankari   
Crave Bit Cafe                   NaN           JP Nagar   
Starbucks                        3.9  Bannerghatta Road   
Kolkata Kathi Rolls              3.8           JP Nagar   
Berrylicious                     3.8           JP Nagar   
Punjabi Dhaba                    3.5            Ejipura   
Hunger House 32                  NaN            Ejipura   
Palmgrove                        4.0     Residency Road   
Hotel Kanchan's Fish & Chicken   3.3       Shivajinagar   

                                                                       dish_liked  \
name                                                                                
Spice Elephant                  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   
Burger King                                                                   NaN   
Ande Ka Funda                                                                 NaN   
Crave Bit Cafe                                                                NaN   
Starbucks                                                                     NaN   
Kolkata Kathi Rolls                                                           NaN   
Berrylicious                                    Macaroon, Brownie Sundae, Waffles   
Punjabi Dhaba                                             Butter Chicken, Paratha   
Hunger House 32                                                               NaN   
Palmgrove                       Masala Dosa, Naan, Pongal, Grape Juice, Kulcha...   
Hotel Kanchan's Fish & Chicken                                                NaN   

                                                                cuisines  \
name                                                                       
Spice Elephant                                 Chinese North Indian Thai   
Burger King                                   Burger Fast Food Beverages   
Ande Ka Funda                               North Indian Fast Food Rolls   
Crave Bit Cafe                                                      Cafe   
Starbucks                                                  Cafe Desserts   
Kolkata Kathi Rolls                                                Rolls   
Berrylicious                                   Ice Cream Desserts Bakery   
Punjabi Dhaba                                       North Indian Chinese   
Hunger House 32                                     North Indian Chinese   
Palmgrove                       North Indian South Indian Chinese Juices   
Hotel Kanchan's Fish & Chicken                      South Indian Chinese   

                                approx_cost      neighbourhood  \
name                                                             
Spice Elephant                        800.0       Banashankari   
Burger King                           600.0       Banashankari   
Ande Ka Funda                         250.0       Banashankari   
Crave Bit Cafe                        600.0  Bannerghatta Road   
Starbucks                             700.0  Bannerghatta Road   
Kolkata Kathi Rolls                   150.0  Bannerghatta Road   
Berrylicious                          400.0  Bannerghatta Road   
Punjabi Dhaba                         350.0       Brigade Road   
Hunger House 32                       300.0       Brigade Road   
Palmgrove                             700.0       Brigade Road   
Hotel Kanchan's Fish & Chicken        250.0       Brigade Road   

                                                               addr  
name                                                                 
Spice Elephant                            Banashankari Banashankari  
Burger King                               Banashankari Basavanagudi  
Ande Ka Funda                 

In [44]:
cosine_similarity([sim[11]],[sim[0]])

array([[0.99999857]], dtype=float32)